### ISSUE TITLE
Issue preventing the m3u and epg file creation

### ISSUE THREAD

**Issue by fennemaj** [maddox/pluto-for-channels#11]
There seems to be an issue that I'm encountering which is preventing the creation of the m3u and epg files.  Below is the information in the docker logs.  The Playlist and EPG links both generate 404 errors because the files are not being created as a result of the error.

INFO] Grabbing EPG...
http://api.pluto.tv/v2/channels?start=2021-02-02%2020%3A00%3A00.000%2B0000&stop=2021-02-03%2002%3A00%3A00.000%2B0000
http://api.pluto.tv/v2/channels?start=2021-02-03%2002%3A00%3A00.000%2B0000&stop=2021-02-03%2008%3A00%3A00.000%2B0000
http://api.pluto.tv/v2/channels?start=2021-02-03%2008%3A00%3A00.000%2B0000&stop=2021-02-03%2014%3A00%3A00.000%2B0000
http://api.pluto.tv/v2/channels?start=2021-02-03%2014%3A00%3A00.000%2B0000&stop=2021-02-03%2020%3A00%3A00.000%2B0000
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
at JSON.parse ()
at Request._callback (/usr/src/app/index.js:70:24)
at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
at Request.emit (events.js:210:5)
at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
at ClientRequest.emit (events.js:210:5)
at Socket.socketErrorListener (_http_client.js:407:9)
at Socket.emit (events.js:210:5)
at emitErrorNT (internal/streams/destroy.js:84:8)
at processTicksAndRejections (internal/process/task_queues.js:80:21)

mv: can't rename '*playlist.m3u': No such file or directory
mv: can't rename '*epg.xml': No such file or directory
Last ran: Tue Feb 2 20:49:20 UTC 2021

**Comment by bearxor** [comment]
Had the same issue. Did a little digging and logged in to the console and ran
`cd /usr/share/nginx/html
npx pluto-iptv `

This created a playlist.m3u8 and epg.xml in the directory that I could point channels at (had to modify the extension to m3u8). I was a little curious and stopped the container and restarted it. Once restarted everything appeared to work fine. It even created the playlist.m3u in the html directory.

Maybe it just doesn't work on first boot?

**Comment by maddox** [comment]
The project writes a `playlist.m3u` file and moves it. If your version is actually creating an `m3u8` file on disk, then your docker image may be out of date. Be sure you're on the latest.

**Comment by bearxor** [comment]
no - the issue was that it wasn't writing anything. I've pulled this a few times over the last couple of weeks and it never works, i get the same error message as @fennemaj. It never worked.

Finally i got curious and looked up the original PlutoXML project and saw I could run the npx command. I ran it and that generated the m3u8 file.

When I rebooted the container, then everything actually worked and I got the m3u file and it moved it in the right direction.

It doesn't matter how many times I pull a copy of your container - it always errors out. I just set up a new container and heres what i get

![Screen Shot 2021-04-12 at 3 09 12 PM](https://user-images.githubusercontent.com/3756220/114448115-1fc55c80-9ba1-11eb-9a4a-be34aab31e4a.png)

**Comment by maddox** [comment]
Hmm, it's not writing anything because it's throwing an error. So there's something else going on. Having just run it, it didn't error for me though.

**Comment by bearxor** [comment]
I've played with this a little bit more - if i deploy the container in bridge mode, it works perfectly fine. If I assign it a network adapter and give it an ip address on my network, it errors out.

@fennemaj are you also trying to assign the container an ip?

**Comment by cory9214** [comment]
Having the same issue. Any new guidance here?

![Screen Shot 2021-09-11 at 00 13 19](https://user-images.githubusercontent.com/14288011/132939876-270dda2c-e0cd-4d37-b983-dafd0f42ebc8.png)
