### ISSUE TITLE
'clip' property is null preventing m3u/epg creation

### ISSUE THREAD

**Issue by lymanepp** [maddox/pluto-for-channels#12]
```
[INFO] Adding instance of LUCHA LIBRE AAA: SPECIAL EVENT  REY DE REYES to channel Lucha Libre AAA.
[INFO] Adding instance of LUCHA LIBRE AAA to channel Lucha Libre AAA.
[INFO] Adding instance of LUCHA LIBRE AAA to channel Lucha Libre AAA.
[INFO] Adding instance of LUCHA LIBRE AAA to channel Lucha Libre AAA.
[INFO] Adding instance of LUCHA LIBRE AAA to channel Lucha Libre AAA.
/usr/src/app/index.js:235
                text: moment(programme.episode.clip.originalReleaseDate).format('YYYYMMDD'),
                                                    ^

TypeError: Cannot read property 'originalReleaseDate' of null
    at /usr/src/app/index.js:235:53
    at Array.forEach (<anonymous>)
    at /usr/src/app/index.js:188:27
    at Array.forEach (<anonymous>)
    at processChannels (/usr/src/app/index.js:171:12)
    at /usr/src/app/index.js:322:5
    at Object.grabJSON (/usr/src/app/index.js:39:9)
    at /usr/src/app/index.js:321:13
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/usr/src/app/index.js:320:10)

mv: can't rename '*playlist.m3u': No such file or directory
mv: can't rename '*epg.xml': No such file or directory
```

**Comment by maddox** [comment]
Fixed in 28afff4b24b40204234186ce7f72b25bf026c246

**Comment by lymanepp** [comment]
That fixed it! Thank you!

**Comment by maddox** [comment]
🎉
