### ISSUE TITLE
Error on EPG

### ISSUE THREAD

**Issue by rapteev** [maddox/pluto-for-channels#16]
Hi
My EPG is not updating.
Error from docker logs is>

PS C:\Windows\system32> docker logs pluto-for-channels
[INFO] Grabbing EPG...
http://api.pluto.tv/v2/channels?start=2021-05-03%2013%3A00%3A00.000%2B0000&stop=2021-05-03%2019%3A00%3A00.000%2B0000
http://api.pluto.tv/v2/channels?start=2021-05-03%2019%3A00%3A00.000%2B0000&stop=2021-05-04%2001%3A00%3A00.000%2B0000
http://api.pluto.tv/v2/channels?start=2021-05-04%2001%3A00%3A00.000%2B0000&stop=2021-05-04%2007%3A00%3A00.000%2B0000
http://api.pluto.tv/v2/channels?start=2021-05-04%2007%3A00%3A00.000%2B0000&stop=2021-05-04%2013%3A00%3A00.000%2B0000
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/src/app/index.js:120:26)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:210:5)
    at Socket.socketErrorListener (_http_client.js:407:9)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

mv: can't rename '*playlist.m3u': No such file or directory
Last ran: Mon May  3 13:37:17 UTC 2021
mv: can't rename '*epg.xml': No such file or directory
2021/05/03 13:37:41 [error] 10#10: *1 open() "/usr/share/nginx/html/playlist.m3u" failed (2: No such file or directory), client: 192.168.1.250, server: localhost, request: "GET /playlist.m3u HTTP/1.1", host: "192.168.1.250:7979"
192.168.1.250 - - [03/May/2021:13:37:41 +0000] "GET /playlist.m3u HTTP/1.1" 404 153 "-" "Go-http-client/1.1" "-"
2021/05/03 13:38:02 [error] 10#10: *2 open() "/usr/share/nginx/html/epg.xml" failed (2: No such file or directory), client: 192.168.1.250, server: localhost, request: "GET /epg.xml HTTP/1.1", host: "192.168.1.250:7979"
192.168.1.250 - - [03/May/2021:13:38:02 +0000] "GET /epg.xml HTTP/1.1" 404 153 "-" "Mozilla/5.0 ChannelsDVR+XMLTV/1.0" "-"
192.168.1.250 - - [03/May/2021:13:42:38 +0000] "GET /playlist.m3u HTTP/1.1" 404 153 "-" "Go-http-client/1.1" "-"
2021/05/03 13:42:38 [error] 10#10: *3 open() "/usr/share/nginx/html/playlist.m3u" failed (2: No such file or directory), client: 192.168.1.250, server: localhost, request: "GET /playlist.m3u HTTP/1.1", host: "192.168.1.250:7979"
192.168.1.250 - - [03/May/2021:13:42:41 +0000] "GET /epg.xml HTTP/1.1" 404 153 "-" "Mozilla/5.0 ChannelsDVR+XMLTV/1.0" "-"
2021/05/03 13:42:41 [error] 10#10: *4 open() "/usr/share/nginx/html/epg.xml" failed (2: No such file or directory), client: 192.168.1.250, server: localhost, request: "GET /epg.xml HTTP/1.1", host: "192.168.1.250:7979"

**Comment by rapteev** [comment]
I reinstalled Pluto for channels docker and the issue is gone.
Probably some thing go wrong on my Windows machine.
Thank you anyway
