### ISSUE TITLE
Referencing property of null object results in guide not building

### ISSUE THREAD

**Issue by cstraw** [maddox/pluto-for-channels#5]
[INFO] Adding instance of Monkey King 2 to channel Flicks of Fury.
[INFO] Adding instance of Tsui Hark's Vampire Hunters to channel Flicks of Fury.
[INFO] Adding instance of Detective Dee and the Mystery of the Phantom Flame to channel Flicks of Fury.
[INFO] Adding instance of Detective Dee and the Mystery of the Phantom Flame to channel Flicks of Fury.
[INFO] Adding instance of Executioners From Shaolin to channel Flicks of Fury.
/usr/src/app/index.js:207
            airingArt = programme.episode.poster.path
                                                 ^
TypeError: Cannot read property 'path' of undefined
    at /usr/src/app/index.js:207:50
    at Array.forEach (<anonymous>)
    at /usr/src/app/index.js:182:27
    at Array.forEach (<anonymous>)
    at /usr/src/app/index.js:165:12
    at Object.grabJSON (/usr/src/app/index.js:33:9)
    at Object.<anonymous> (/usr/src/app/index.js:99:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
mv: can't rename 'playlist.m3u': No such file or directory
mv: can't rename 'epg.xml': No such file or directory
Last ran: Sun Dec 27 00:28:42 UTC 2020

**Comment by dschaper** [comment]
See #4
